const {app,BrowserWindow,ipcMain,shell,dialog}=require('electron');
const path=require('path'),fs=require('fs'),https=require('https');
function win(){const w=new BrowserWindow({width:1050,height:700,minWidth:850,minHeight:560,backgroundColor:'#080b10',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});w.loadFile(path.join(__dirname,'index.html'));}
function get(url){return new Promise((resolve,reject)=>{https.get(url,{headers:{'User-Agent':'NeonCraftLauncher/1.0'}},r=>{if([301,302,307,308].includes(r.statusCode)&&r.headers.location)return get(r.headers.location).then(resolve,reject);let d=[];r.on('data',x=>d.push(x));r.on('end',()=>resolve(Buffer.concat(d)));}).on('error',reject)})}
async function json(url){return JSON.parse((await get(url)).toString())}
function download(url,out){return new Promise((resolve,reject)=>{https.get(url,{headers:{'User-Agent':'NeonCraftLauncher/1.0'}},r=>{if([301,302,307,308].includes(r.statusCode)&&r.headers.location)return download(r.headers.location,out).then(resolve,reject);if(r.statusCode!==200)return reject(new Error('Download HTTP '+r.statusCode));const f=fs.createWriteStream(out);r.pipe(f);f.on('finish',()=>f.close(resolve));}).on('error',reject)})}
async function installMods(mc){const dir=path.join(mc,'mods');fs.mkdirSync(dir,{recursive:true});const projects=['sodium','sodium-extra','lithium','ferrite-core','immediatelyfast'];const done=[];for(const p of projects){const vs=await json(`https://api.modrinth.com/v2/project/${p}/version?game_versions=[%221.21.11%22]&loaders=[%22fabric%22]&limit=1`);if(!vs.length)continue;const file=vs[0].files.find(x=>x.primary)||vs[0].files[0];if(!file)continue;await download(file.url,path.join(dir,file.filename));done.push(file.filename)}return done}
ipcMain.handle('find-minecraft',()=>{const p=path.join(process.env.APPDATA||'', '.minecraft');return fs.existsSync(p)?p:null});
ipcMain.handle('install',async()=>{let mc=path.join(process.env.APPDATA||'', '.minecraft');if(!fs.existsSync(mc)){const r=await dialog.showOpenDialog({properties:['openDirectory'],title:'Select your .minecraft folder'});if(r.canceled)return {ok:false};mc=r.filePaths[0]}try{return {ok:true,files:await installMods(mc),folder:mc}}catch(e){return {ok:false,error:e.message}}});
ipcMain.handle('open-minecraft',async()=>{try{await shell.openExternal('minecraft://');return true}catch{return false}});
ipcMain.handle('open-folder',(_,p)=>shell.openPath(p));
app.whenReady().then(()=>{win();app.on('activate',()=>{if(!BrowserWindow.getAllWindows().length)win()})});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
